### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by fepegar** [JoostJM/SlicerCaseIterator#15]
Hello,

I got this error on startup:

```python-traceback
Python 3.6.7 (default, Mar 24 2020, 03:05:54) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
>>> 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fernando/.config/NA-MIC/Extensions-28875/SlicerCaseIterator/lib/Slicer-4.11/qt-scripted-modules/SlicerCaseIterator.py", line 19, in <module>
    from SlicerDevelopmentToolboxUtils.buttons import *
ModuleNotFoundError: No module named 'SlicerDevelopmentToolboxUtils'
```

**Comment by JoostJM** [comment]
Hi @fepegar, 

Thanks for reporting this issue. For now what you can do to fix it is to install SlicerDevelopmentToolboxUtils, which is a module you can install just like SlicerCaseIterator.
I'll try to update the Iterator code to include this module in it's dependencies, so this does not keep popping up.

**Comment by fepegar** [comment]
Ok, thanks!

**Comment by JoostJM** [comment]
@che85, can you see if you can add the SlicerDevelopmentToolboxUtils module to SlicerCaseIterator's dependencies?

**Comment by JoostJM** [comment]
Fixed by #17
