### ISSUE TITLE
Extension fails in slicer 4.10

### ISSUE THREAD

**Issue by kayarre** [JoostJM/SlicerCaseIterator#3]
SlicerCaseIterator fails in latest release of 3dSlicer.

```
~/tools/Slicer-4.10.0-linux-amd64/Slicer
  Error(s):
    CLI executable: /home/sansomk/.config/NA-MIC/Extensions-27501/SlicerCaseIterator/lib/Slicer-4.10/qt-scripted-modules/SlicerCaseIterator.py
    The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
Fail to instantiate module  "SlicerCaseIterator"
```

I also made the script executable and got the following error:
```
  Error(s):
    CLI executable: /home/sansomk/.config/NA-MIC/Extensions-27501/SlicerCaseIterator/lib/Slicer-4.10/qt-scripted-modules/SlicerCaseIterator.py
    Traceback (most recent call last):
  File "/home/sansomk/.config/NA-MIC/Extensions-27501/SlicerCaseIterator/lib/Slicer-4.10/qt-scripted-modules/SlicerCaseIterator.py", line 21, in <module>
    import vtk, qt, ctk, slicer
  File "/home/sansomk/tools/Slicer-4.10.0-linux-amd64/lib/Slicer-4.10/python2.7/site-packages/vtk.py", line 12, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "/home/sansomk/tools/Slicer-4.10.0-linux-amd64/lib/Python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sansomk/tools/Slicer-4.10.0-linux-amd64/lib/Slicer-4.10/python2.7/site-packages/vtkmodules/all.py", line 7, in <module>
    from .vtkCommonKit import *
  File "/home/sansomk/tools/Slicer-4.10.0-linux-amd64/lib/Slicer-4.10/python2.7/site-packages/vtkmodules/vtkCommonKit.py", line 9, in <module>
    from vtkCommonKitPython import *
ImportError: No module named vtkCommonKitPython

    CLI executable: /home/sansomk/.config/NA-MIC/Extensions-27501/SlicerCaseIterator/lib/Slicer-4.10/qt-scripted-modules/SlicerCaseIterator.py
    Failed to retrieve Xml Description
Fail to instantiate module  "SlicerCaseIterator"

```

**Comment by kayarre** [comment]
The problem is the line:
```
#!/usr/bin/env python
```
removing it fixes the issue.

**Comment by JoostJM** [comment]
@kayarre, @lassoan proposed a fix, which will be included in the next nightly build. Thanks for the catch!
